### PR TITLE
added fallbackCoverColor param in .toml

### PR DESCRIPTION
**Pull request by KSLHacks**
Added ability to set the site background color through the `config.toml`.

The user is not able to view the text on the left pane during the delay time for the the `coverImage` to load. The white text blends with the white background of the website. This parameter will allow the text to still be visible during the load time.

- Added `fallbackCoverColor` to `config.toml`
- Added parameter description and example value in `exampleSite/config.toml`
- Kept logic in `cover.html` the same, but added the color background value and `background-size` so all images fit on the page.

Collaboration with @howlowck

### CODE REVIEW

**Comment by kakawait** [comment]
@KSLHacks Thank you for contribution I will check that this week

**Comment by howlowck** [comment]
👍

**Comment by KSLHacks** [comment]
Updated branch.. removed extra content. Ready for review 😄

**Comment by kakawait** [comment]
@KSLHacks Sorry I didn't find time to check that this week as I said 😭 Excuse me.

I will merge it before Thursday because after I have a 4 days break :)

**Comment by jhabdas** [comment]
@kakawait unsubscribing to help focus on new business. feel free to ping if you need any opinions on anything. i'm full of them.

**Pull request merged**
