### PR TITLE
Update the compatibility version of Hugo (from 0.30 to 0.53)

### PR DESCRIPTION
**Pull request by xenlo**
Solve #362

### CODE REVIEW

**Comment by kakawait** [comment]
@xenlo thank for work. I'll in vacation for 4 weeks without internet access. So don't be afraid about no new but I'll merge it asap.

**Comment by xenlo** [comment]
Il n'y a pas d'urgence.

Bonne vacances!

**Comment by xenlo** [comment]
I committed a change on the example post article to add the type in the metadata. It solve the issue #365

**Comment by kakawait** [comment]
@xenlo I do a hotfix release for something else so I just updated doc as you propose on your first commit of that MR 

See https://github.com/kakawait/hugo-tranquilpeak-theme/pull/372/commits/d6d100a09d5f1eacc76ccc1c50c2f077bc9a1e6a

But I keep it open because you push other thing that I'll review after vacations

**Comment by kakawait** [comment]
I'll close it because was fixed by hotfix and _main section_ stuffs was changed on `0.5.0-BETA` so I don't think is needed anymore.

Thank you for your work that help a lot to create the Hotfix.

**Pull request closed without merging**
