### PR TITLE
fix long id in gitalk

### LINKED ISSUE #507: Validation Failed(422) found in gitalk
Here comes the second issues. Please let me fix it if needed this time.

### Actual behavior
 I use gitalk in Chinese language.  And the URI encoding makes the parameter named _id_  pretty long（more than 50 chars）which results in Validation Failed （422）

```
new Gitalk({
          clientID: '{{ .Site.Params.comment.gitalk.clientId }}',
          clientSecret: '{{ .Site.Params.comment.gitalk.clientSecret }}',
          repo: '{{ .Site.Params.comment.gitalk.repo }}',
          owner: '{{ .Site.Params.comment.gitalk.owner }}',
          admin: ['{{ .Site.Params.comment.gitalk.owner }}'],
          id: '{{ .RelPermalink }}',  // Ensure uniqueness and length less than 50
          ...{{ .Site.Params.comment.gitalk.options | jsonify | safeJS }}
        }).render('gitalk')
```
### How to fix

wrapper  _{{ .RelPermalink }}_ by decodeURI function.

e.g. 
image

image

### PR DESCRIPTION
**Pull request by duval1024**
decode uri for gitalk

fixes #507

### CODE REVIEW

**Comment by duval1024** [comment]
Please check this pull request. It is my first pull request. I am not sure if it is correct. 

Thank you very much!

**Comment by kakawait** [comment]
The problem with `decodeURI` is that it will work with your use case but not for all.

The main problem is that `id` must be unique **and not more 50 chars**.

What we can do in place of `decodeURI` is using hash function like `md5` or `sha1`

Can you please check?

**Comment by duval1024** [comment]
I agree with you. The best way to fix it is md5 or sha1. I will try later

**Comment by duval1024** [comment]
@kakawait  hi，I have changed it to md5 function. Please check. Thx~

**Pull request merged**
