### PR TITLE
Improved twitter cards

### PR DESCRIPTION
**Pull request by sergiandreplace**
Tagging of twitter cards was not really working fine (at least for me)

Added some values to make it more flexible/automated

### CODE REVIEW

**Comment by kakawait** [comment]
@sergiandreplace thank you for contribution. I will check that asap. Because I was plan to move _in-house_ SSO feature like _twitter card_ to https://github.com/gohugoio/hugo/blob/142558719324aa1628541d556ef1fa2d123f1e68/tpl/tplimpl/template_embedded.go#L159 (related to #54)

I should see if it will be compatible, if not I have to found a better solution to mix both world

**Comment by sergiandreplace** [comment]
Sure! Take your time for the best solution

**Comment by kakawait** [comment]
@sergiandreplace sorry for delay. After more research i think I will not use Hugo internal template in ordre to keep control of Social tag.

I'm currently working on it because I want to merge with other PR #216 

Promise i will fix/enhance twitter card (Aka social tag) really soon. I already have a branch on local workspace

**Comment by kakawait** [comment]
I will close it in favor of #239

**Pull request closed without merging**
