### PR TITLE
Added possibilities to make page more customizable.

### PR DESCRIPTION
**Pull request by blaubaer**
Added possibilities to make page more customizable.
1. Show/hide pagination per page.
2. Show/hide social buttons for Twitter, Facebook, ... per page.
3. Show/hide page tags per page.
4. Make sidebar author avatar link modifiable

### CODE REVIEW

**Comment by kakawait** [comment]
@blaubaer thank you for contribution. I'm actually in vacancies without computer I will not able to review PR before 2017 sorry !

**Comment by kakawait** [comment]
@blaubaer Could you please add a static sample page on `exampleSite`?

**Comment by blaubaer** [comment]
Sure - good idea. I will do this as fast as possible. :-)

**Comment by kakawait** [comment]
Don't worry, take your time is new year 👍 

PS: Happy new year 🎉

**Comment by blaubaer** [comment]
Is this like your expectations? The only thing I'am currently not completely lucky with: I used the same thumbnail image. Do you have some other available to add to make the example looks nicer?

**Comment by kakawait** [comment]
I don't have thumbnail in my pocket for now but I can find a new one. I will check that and try it asap (before tomorrow end of the day GMT+1).

Thank you again

**Comment by kakawait** [comment]
@blaubaer Merged on `develop` I will release a new version `0.2.1-ALPHA` at the end of the week, just some few bugs to fix before releasing

**Pull request merged**
