### PR TITLE
Add separate styling for static pages

### PR DESCRIPTION
**Pull request by Martin1001**
- additional page type "page"
- pages are not contains meta (e.g. date), disqus, back& forward buttons

### CODE REVIEW

**Comment by Martin1001** [comment]
#60

**Comment by kakawait** [comment]
Thank I will check that asap

**Comment by kakawait** [comment]
@Martin1001 Sorry for delay, I have not many time at the end of this year ⏲ 

Can you add some sample on `exampleSite` folder?

**Comment by Martin1001** [comment]
At the weekend I will attach the examples.

**Pull request closed without merging**
